UV_CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import landing

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('', landing)

]

leads/urls.py
from django.urls import path
from .views import *

app_name = "leads"

urlpatterns = [
    path('', leads_list, name="lead-list"),
    path('create', lead_create, name="lead-create"),
    path('<pk>', lead_detail, name="lead-detail"),
    path('update/<pk>', lead_update_view, name="lead-update"),
    path('delete/<pk>', lead_del, name="lead-delete")
]

leads/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser


# Getting a phone number field that respects the E.164 Will help later with SMS Automation Integration
# https://en.wikipedia.org/wiki/E.164
# https://github.com/stefanfoulis/django-phonenumber-field


# class User(AbstractUser):
#     pass


class Lead(models.Model):
    name = models.CharField(max_length=50)
    url = models.URLField(max_length=400)
    email = models.EmailField(max_length=50, null=True)
    number = PhoneNumberField(blank=True, null=True)
    contacted = models.BooleanField(default=False)
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class Agent(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name + " " + self.last_name

leads/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from .models import Agent, Lead


# name = models.CharField(max_length=50)
#     url = models.URLField(max_length=400)
#     email = models.EmailField(max_length=50, null=True)
#     number = PhoneNumberField(blank=True, null=True)
#     contacted = models.BooleanField(default=False)
#     agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)
#


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "name",
            "number",
            "email",
            "agent",
            "url"
        )


class LeadForm(forms.Form):
    name = forms.CharField()
    url = forms.URLField()
    email = forms.EmailField()
    number = PhoneNumberField()

leads/views.py
from django.shortcuts import render, redirect
from .models import Lead, Agent
from .forms import LeadForm, LeadModelForm


def landing(request):
    return render(request, "landing.html")


def leads_list(request):
    leads = Lead.objects.all()
    context = {
        "leads": leads
    }
    return render(request, "leads/lead_list.html", context)


def lead_detail(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead": lead
    }
    return render(request, "leads/lead_detail.html", context)


def lead_create(request):
    form = LeadModelForm()

    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            print("valid")
            form = LeadModelForm(request.POST)
            form.save()
            return redirect("/leads")

    context = {
        "form": form
    }
    return render(request, "leads/lead_create.html", context)


def lead_update_view(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    context = {
        "form": form,
        "lead": lead

    }
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            print("called")
            return redirect("/leads")

    return render(request, "leads/lead_update.html", context)


def lead_del(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UV_CRM</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
<div class="max-w-7xl mx-auto">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/landing.html
{% extends 'base.html' %}
{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
            <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
                 src="https://dummyimage.com/720x600">
            <div class="text-center lg:w-2/3 w-full">
                <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                    Welcome To UV CRM
                </h1>
                <p class="mb-8 leading-relaxed">This CRM finds you find and manage leads .</p>
                <div class="flex justify-center">
                    <button class="inline-flex text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg">
                        Button
                    </button>
                    <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
                        Button
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/leads/lead_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Create a New Lead</h1>
    <form method="post" action="create">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

templates/leads/lead_detail.html
{% extends 'base.html' %}
{% load leads_tag %}

{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">Company Name</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.name }}</h1>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Email</span>
                        <span class="ml-auto text-gray-900">{{ lead.email }}</span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Number</span>
                        <span class="ml-auto text-gray-900">{{ lead.number }}</span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Website</span>
                        <span class="ml-auto text-gray-900"><a href="{{ lead.url }}">
                                {{ lead.url|reduce_url }}
                        </a> </span>

                    </div>
                    <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                        <span class="text-gray-500">Current Agent</span>
                        {% if lead.agent == None %}
                            <span class="ml-auto text-gray-900">Agent Not Assigned</span>
                        {% else %}
                            <span class="ml-auto text-gray-900">{{ lead.agent }}</span>

                        {% endif %}
                    </div>

                    <div class="flex">
                        <button onclick="window.location.href='{% url 'leads:lead-update' lead.id %}'"
                                class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                            Update Info
                        </button>
                        <button onclick="window.location.href='{% url 'leads:lead-delete' lead.id %}'"
                                class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                            Delete Lead
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/leads/lead_list.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'leads:lead-create' %}">Create Leads</a>
    <hr>
    <h1>These are all our leads</h1>
    <table class="table-fixed">

        <thead>
        <tr>
            <th class="w-1/2 px-4 py-2">Company Name</th>
            <th class="w-1/4 px-4 py-2">URL</th>
            <th class="w-1/4 px-4 py-2">Status(Assigned/Un-Assigned)</th>
        </tr>
        </thead>
        <tbody>
        {% for lead in leads %}

            <tr>
                <td class="border px-4 py-2 ">
                    <a href="{% url 'leads:lead-detail' lead.id %}">
                        {{ lead.name }}
                    </a></td>
                <td class="border px-4 py-2"><a href="{{ lead.url }}">{{ lead.url }}</a></td>
                {% if lead.agent != None %}
                    <td class="border px-4 py-2">
                        <a href="{% url 'leads:lead-update' lead.id %}">

                            <i style="color: green" class="far fa-check-circle"></i>
                        </a>
                    </td>
                {% else %}

                    <td class="border px-4 py-2">
                        <a href="{% url 'leads:lead-update' lead.id %}">
                            <i class="fas fa-user-edit"></i>
                        </a>
                    </td>
                    </td>

                {% endif %}

            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/leads/lead_update.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" action="./{{ lead.id }}">

        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

{% endblock %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round"
                 stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
                 viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">UV CRM</span>
        </a>
        <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a class="mr-5 hover:text-gray-900">First Link</a>
            <a class="mr-5 hover:text-gray-900">Second Link</a>
            <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads List</a>
            <a class="mr-5 hover:text-gray-900">Sign Up</a>
        </nav>
        <a href="$"
           class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Login
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                 class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
    </div>
</header>